# fly.toml app configuration file generated for keygen-api on 2024-07-02T08:25:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'keygen-api'
primary_region = 'lax'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/v1/health"

[processes]
  app = "bin/rails server"
  worker = "bundle exec sidekiq"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ["app"]

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ["worker"]

[deploy]
  strategy = "bluegreen"
